apiVersion: v1
kind: Service
metadata:
  name: fiis-calculator
spec:
  selector:
    app: fiis-calculator
  ports:
  - port: 3000
    nodePort: 31000
    targetPort: fiis-calculator-port
    protocol: TCP
  type: NodePort